import Head from 'next/head'
import Footer from '../Components/Footer';
import Header from '../Components/Header';
import ProjectSection from '../Components/ProjectSection'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <ProjectSection />
      </main>
      <Footer />
    </div>
  );
}
