import Head from 'next/head'
import {
  BsGithub,
  BsInstagram,
  BsLinkedin,
  BsTwitter,
  BsArrowRightShort,
} from "react-icons/bs";


export default function Home() {

  console.log('ok')

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="header  border ">
        <div className="w-16 h-16 rounded-full bg-cover bg-no-repeat bg-center bg-[url('../public/kasskoo2.png')]"></div>
        <p>Gérald M'Bahia</p>
        <p>
          Actuellement, je travaille ici <BsArrowRightShort />
          <img
            src="../public/logo_orgganiz.png"
            alt="logo orgganiz"
            className="w-16 h-16"
          />
        </p>
        <p className="uppercase">Hello bro</p>
        <BsGithub />
        <BsInstagram />
        <BsTwitter />
        <BsLinkedin />
      </main>
    </div>
  );
}
